### ISSUE TITLE
membre

### ISSUE THREAD

**Issue by halimgambit** [Seb85/Avatar-Plugin-jarvis#1]
bonjour seb un forum pour avatar a était créeer en plus il y a beaucoup de changement, (certain plugin a supprimer et a modifier) cordialement
https://avatar-ia.forumactif.com/?utm_source=pwa

**Comment by Seb85** [comment]
Bonjour,
Sympa ce petit forum ! Pour ma part j'ai cracké, je suis passé du coté obscur de la force avec la Google Home.

J'utilise Google SmartHome pour piloter ma box domotique jeedom, j'arrive a effectuer toutes les actions que je faisais avec Avatar.

Je continuerai de scruter les nouveautés d'Avatar mais ne poursuivrait pas la création de nouveaux plugins.

Bonne continuation a toi
